baseURL: https://jelena-savic-portfolio.netlify.app
languageCode: en-us
title: Portfolio website for Jelena Savic
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    title: Jelena Savic, LBS MAM Student
  blog: {}
  contact:
    address: 
      - city: Belgrade
        country: Serbia
        street: Knez Mihajlova 5
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jsavic.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 123-0000 1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/jelenaSavic2404
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jelena-savic-39a5871a9/
  image: ''
  name: Your name
  navigation:
    links:
      - name: Home
        url: '#'
      - name: About me
        url: about_me
      - name: Projects
        url: projects
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: comp1.jpg
        subtitle: Click to find out more 
        title: About me
        url: about_me

      - image: projects_img.jpg
        subtitle: Click to find out more 
        title: Projects
        url: projects

