---
title: "Session 4: Homework 2"
author: "Study Group: 12 (Akshat Kacheria, Asli Ceren Memis, Jelena Savic, Shengcheng Liu, Sophia Kalusche)"
date: "2021-09-18"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<pre class="r"><code>#Loading data
weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;) #skipping the missing data</code></pre>
<ol style="list-style-type: decimal">
<li>Select the year and the twelve month variables from the <code>weather</code> dataset.</li>
</ol>
<pre class="r"><code>#Select the data we need
weather_data &lt;- weather %&gt;% 
  select(Year, Jan:Dec)</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Convert the dataframe from wide to ‘long’ format.</li>
</ol>
<pre class="r"><code>#Convert data into long format 
#Names of the columns Jan-Dec will become values of new column &quot;Month&quot;
#Monthly temperature deviations stored in column &quot;delta&quot;
tidyweather &lt;- weather_data %&gt;% 
  pivot_longer(cols=c(&quot;Jan&quot;,&quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dec&quot;), names_to=&quot;Month&quot;, values_to=&quot;delta&quot;) 

glimpse(tidyweather) #preview tidied dataset</code></pre>
<pre><code>## Rows: 1,704
## Columns: 3
## $ Year  &lt;dbl&gt; 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880~
## $ Month &lt;chr&gt; &quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, &quot;~
## $ delta &lt;dbl&gt; -0.34, -0.50, -0.22, -0.29, -0.05, -0.15, -0.17, -0.25, -0.22, -~</code></pre>
<pre class="r"><code>#Resulting dataframe has 3 columns: Year, Month and delta</code></pre>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trendline. To do that, we first need to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</p>
<pre class="r"><code>#Mutate the date 
tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)))

tidyweather &lt;- tidyweather %&gt;%
  mutate(
         month = lubridate::month(date, label=TRUE, abbr=TRUE),
         year = year(date))

#Create the graph-temperature deviation by date
ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather anomalies over time&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/scatter_plot-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Is the effect of increasing temperature more pronounced in some months?
<img src="{{< blogdown/postref >}}index_files/figure-html/facet_wrap-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>It is sometimes useful to group data into different time periods to study historical data. For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time. NASA calculates a temperature anomaly, as difference form the base period of 1951-1980. The code below creates a new data frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.</p>
<p>We remove data before 1800 and before using <code>filter</code>. Then, we use the <code>mutate</code> function to create a new variable <code>interval</code> which contains information on which period each observation belongs to.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  
  #remove years prior to 1881
  filter(Year&gt;= 1881) %&gt;%    
  
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in.</p>
<pre class="r"><code>#Distribution of monthly deviations grouped by interval
ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;         #changing y-axis label to sentence case
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/density_plot-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  
  #grouping data by Year
  group_by(Year) %&gt;%   
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta = mean(delta, na.rm=TRUE)) 

#plotting the data
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;,
    y     = &quot;Average Annual Delta&quot;
  )                         </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/averaging-1.png" width="768" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>Your task is to construct a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 

  # choose the interval 2011-present 
  # what dplyr verb will you use? --&gt; Use filter to select 2011-present 
  filter(interval==&quot;2011-present&quot;, !is.na(delta)) %&gt;% 

  # calculate summary statistics for temperature deviation (delta) 
  # calculate mean, SD, count, SE, lower/upper 95% CI
  # what dplyr verb will you use? --&gt; summarize and specify the summary statistics we want to calculate 
  
  summarise(mean=mean(delta), 
            sd=sd(delta), 
            count=n(), 
            se = sd/sqrt(count),  
            t_critical=qt(0.975, count - 1 ), 
            lower = mean-t_critical*se, 
            upper = mean+t_critical*se )
  

#print out formula_CI
formula_ci</code></pre>
<pre><code>## # A tibble: 1 x 7
##    mean    sd count     se t_critical lower upper
##   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  1.06 0.274   128 0.0243       1.98  1.01  1.11</code></pre>
<pre class="r"><code># use the infer package to construct a 95% CI for delta

set.seed(1)

bootstrap_ci &lt;- comparison %&gt;% 
  
  # Select interval of time and eliminate na
  filter(interval==&quot;2011-present&quot;, !is.na(delta)) %&gt;% 
  
  # Specify response as delta 
  infer::specify(response=delta) %&gt;% 

  # Generate bootstrap samples
  infer::generate(reps= 1000, type = &quot;bootstrap&quot;) %&gt;% 
  
  # Find the mean of each sample
  infer::calculate(stat=&quot;mean&quot;)

  # Calculate CI
  percentile_ci &lt;- bootstrap_ci %&gt;% 
  get_confidence_interval(level=0.95, type=&quot;percentile&quot;)

  # Print CI
  percentile_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.01     1.11</code></pre>
<blockquote>
<p>What is the data showing us?</p>
</blockquote>
<p>For the CI calculated by formula, we calculated the critical t-value for 95% confidence level, the mean and SE to manually calculate the CI using the formula CI = mean +/- (critical_t) * SE. For the bootstrap we essentially took a sample of 1000 observations with replacement from the entire pool of observations and used that sample to derive the confidence interval.</p>
<p>The confidence interval for both methods were the same. The result can be interpreted as the following: We are 95% confident that the interval of (1.01, 1.11) captures the true average annual delta in the time interval of 2011-present. Given that the NASA argues that a one-degree increase is significant, as it takes vast amount of heat to warm all the oceans, atmosphere, and land by that much, we can concluded that the earth temperature has indeed significantly increased over the last years.</p>
</div>
</div>
<div id="general-social-survey-gss" class="section level1">
<h1>General Social Survey (GSS)</h1>
<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviors, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>In this assignment we analyze data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and you are using a smaller file.</p>
<pre class="r"><code>#Load the data
gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;))</code></pre>
<p>You will also notice that many responses should not be taken into consideration, like “No Answer”, “Don’t Know”, “Not applicable”, “Refused to Answer”.</p>
<p>We will be creating 95% confidence intervals for population parameters. The variables we have are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</li>
<li><code>sex</code>: Female - Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>Can we estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not. If the recorded value was NA for both of these questions, the value in your new variable should also be NA.</li>
</ol>
<pre class="r"><code>#Create yes/no/NA snap_insta variable using case_when
gss &lt;- gss %&gt;% mutate(snap_insta = case_when(
  snapchat  == &quot;Yes&quot; ~ &quot;Yes&quot;, 
  instagrm  == &quot;Yes&quot; ~ &quot;Yes&quot;, 
  (instagrm  == &quot;No&quot;  &amp;  snapchat  == &quot;NA&quot;) ~ &quot;No&quot;,
  (instagrm  == &quot;NA&quot;  &amp;  snapchat  == &quot;No&quot;) ~ &quot;No&quot;, 
  (instagrm  == &quot;No&quot;  &amp;  snapchat  == &quot;No&quot;) ~ &quot;No&quot;,
  (instagrm  == &quot;NA&quot;  &amp;  snapchat  == &quot;NA&quot;) ~ &quot;NA&quot;))</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</li>
</ol>
<pre class="r"><code>  # Filter out NA
  gss_proportion &lt;- gss %&gt;% filter(!snap_insta == &quot;NA&quot;) %&gt;% 
   
  # Group by snap_insta
  group_by(snap_insta) %&gt;% 
  
  # Count yes and no 
  summarize(count=n()) %&gt;% 
  
  # Calculate proportion
  mutate(proportion= count/sum(count)*100)

  #Print proportion 
  gss_proportion</code></pre>
<pre><code>## # A tibble: 2 x 3
##   snap_insta count proportion
##   &lt;chr&gt;      &lt;int&gt;      &lt;dbl&gt;
## 1 No           858       62.5
## 2 Yes          514       37.5</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Using the CI formula for proportions, please construct 95% CIs for men and women who used either Snapchat or Instagram.</li>
</ol>
<pre class="r"><code>  # Filter out NA
  boot_snap_insta &lt;- gss %&gt;% filter(!snap_insta == &quot;NA&quot;) %&gt;% 
  
  #Change categorical values to binomial 
  mutate(snap_insta_b = case_when( 
    snap_insta == &quot;Yes&quot; ~ 1,
    snap_insta == &quot;No&quot; ~ 0)) %&gt;% 
  
  #Group by sex
  group_by(sex) %&gt;% 
    
  #Calculate needed summary statistics
  summarise(mean=mean(snap_insta_b),
            number=n(), 
            sample_count_yes = count(snap_insta_b==1),
            sample_proportion_yes = sample_count_yes/number,
            se = sqrt((sample_proportion_yes*(1-sample_proportion_yes))/number),  
            t_critical=qt(0.975, number- 1 ), 
            lower = mean-t_critical*se, 
            upper = mean+t_critical*se )

  #Print summary statiscs 
  boot_snap_insta</code></pre>
<pre><code>## # A tibble: 2 x 9
##   sex     mean number sample_count_yes sample_proportio~     se t_critical lower
##   &lt;chr&gt;  &lt;dbl&gt;  &lt;int&gt;            &lt;int&gt;             &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
## 1 Female 0.419    769              322             0.419 0.0178       1.96 0.384
## 2 Male   0.318    603              192             0.318 0.0190       1.96 0.281
## # ... with 1 more variable: upper &lt;dbl&gt;</code></pre>
<pre class="r"><code>  #Store confidence interval 
  confidence_interval_snap_insta &lt;- boot_snap_insta %&gt;%  select(sex, lower, upper)
  confidence_interval_snap_insta </code></pre>
<pre><code>## # A tibble: 2 x 3
##   sex    lower upper
##   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 Female 0.384 0.454
## 2 Male   0.281 0.356</code></pre>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>Can we estimate the <em>population</em> proportion of Twitter users by education level in 2016?.</p>
<p>There are 5 education levels in variable <code>degree</code> which, in ascending order of years of education, are Lt high school, High School, Junior college, Bachelor, Graduate.</p>
<ol style="list-style-type: decimal">
<li>Turn <code>degree</code> from a character variable into a factor variable. Make sure the order is the correct one and that levels are not sorted alphabetically which is what R by default does.</li>
<li>Create a new variable, <code>bachelor_graduate</code> that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree. As before, if the recorded value for either was NA, the value in your new variable should also be NA.</li>
<li>Calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</li>
<li>Using the CI formula for proportions, please construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</li>
<li>Do these two Confidence Intervals overlap?</li>
</ol>
<p><em>Answer:</em> The confidence intervals do not overlap, hence there appears to be a significant different of twitter usage depending on education.</p>
<pre class="r"><code># 1. Turn degree into a factor variable 
education_level &lt;- gss %&gt;%  
  mutate(degree=as.factor(degree)) %&gt;% 

# 2. Create bachelor_graduate variable 
mutate(bachelor_graduate = case_when(
  degree == &quot;Bachelor&quot; | degree == &quot;Graduate&quot; ~ &quot;Yes&quot;,
  degree == &quot;NA&quot;  ~ &quot;NA&quot;, 
  TRUE ~ &quot;No&quot;))


education_level_twitter &lt;- education_level %&gt;% 
  # Filter out NA for bachelor graduate and twitter 
  filter(!bachelor_graduate==&quot;NA&quot;, !(twitter)==&quot;NA&quot;) %&gt;% 
  
  # Change Twitter to Binomial value  
  mutate(twitter_b = case_when( 
  twitter == &quot;Yes&quot; ~ 1,
  twitter == &quot;No&quot; ~ 0 )) %&gt;% 
  
  group_by(bachelor_graduate) %&gt;% 
  
# 3. Calculate the proportion of bachelor graduate, se and confidence interval
  summarize(mean=mean(twitter_b), 
            count=n(), 
            proportion=count(twitter_b==&quot;1&quot;)/count, 
            se=sqrt((proportion*(1-proportion))/count), 
            t_critical=qt(0.975, count- 1 ), 
            lower = mean-t_critical*se, 
            upper = mean+t_critical*se)
            

#View output 
education_level_twitter</code></pre>
<pre><code>## # A tibble: 2 x 8
##   bachelor_graduate  mean count proportion     se t_critical lower upper
##   &lt;chr&gt;             &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 No                0.160   882      0.160 0.0123       1.96 0.136 0.184
## 2 Yes               0.233   489      0.233 0.0191       1.96 0.196 0.271</code></pre>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Can we estimate the <em>population</em> parameter on time spent on email weekly?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable called <code>email</code> that combines <code>emailhr</code> and <code>emailmin</code> to reports the number of minutes the respondents spend on email weekly.</li>
<li>Visualise the distribution of this new variable. Find the mean and the median number of minutes respondents spend on email weekly. Is the mean or the median a better measure of the typical amount of time Americans spend on email weekly? Why?</li>
</ol>
<p><em>Answer:</em> The distribution appears to be heavily skewed right. Hence the median would be a better measure in this case, given that it is more robust to the skewness when compared with the mean.</p>
<ol start="3" style="list-style-type: decimal">
<li>Using the <code>infer</code> package, calculate a 95% bootstrap confidence interval for the mean amount of time Americans spend on email weekly. Interpret this interval in context of the data, reporting its endpoints in “humanized” units (e.g. instead of 108 minutes, report 1 hr and 8 minutes). If you get a result that seems a bit odd, discuss why you think this might be the case.</li>
</ol>
<p><em>Answer:</em> The CI build with the Median has the same upper and lower limit. If we were to change this and use the mean, we would get different limits.</p>
<ol start="4" style="list-style-type: decimal">
<li>Would you expect a 99% confidence interval to be wider or narrower than the interval you calculated above? Explain your reasoning.</li>
</ol>
<p><em>Answer:</em> A 99% confidence interval would be wider as you want to provide more certainty of capturing the true population parameter.</p>
<pre class="r"><code># 1. Report total numbers of email usage 
email_usage &lt;- gss %&gt;% 
  
  #Filter out NA
  filter(!(emailmin==&quot;NA&quot;), !(emailhr==&quot;NA&quot;)) %&gt;% 
  
  #Change chr to numeric and add all minutes 
  mutate(emailmin=as.numeric(emailmin), emailhr=as.numeric(emailhr), email= emailhr*60+emailmin)

# 2a. Mean and median 
email_usage_summary &lt;- email_usage  %&gt;% 
  summarise(mean=mean(email), median=median(email), sd=sd(email))

# Print summary statistics
email_usage_summary</code></pre>
<pre><code>## # A tibble: 1 x 3
##    mean median    sd
##   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1  417.    120  680.</code></pre>
<pre class="r"><code># 2b. plot distribution of email usage
ggplot(data = email_usage, aes(x = email)) + 
  geom_density() + 
  labs(title=&quot;Density plot of average minutes spent on email weekly&quot;, x=&quot;Minutes spent on email&quot;, y=&quot;Density&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/Email%20usage-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code># 3 Bootstrap confidence interval 

#setting the seed so that we can reproduce the same results by repeating the process with the same seed
set.seed(2404)

bootstrap_ci_email &lt;- email_usage %&gt;% 
  
  # Specify response as delta 
  infer::specify(response=email) %&gt;% 

  # Generate bootstrap samples
  infer::generate(reps= 1000, type = &quot;bootstrap&quot;) %&gt;% 
  
  # Find the median of each sample
  infer::calculate(stat=&quot;median&quot;)

  # Calculate CI
  percentile_ci_email &lt;- bootstrap_ci_email %&gt;% 
  infer::get_confidence_interval(level=0.95, type=&quot;percentile&quot;) 
  

  # Print CI and change it to user friendly format 
  percentile_ci_email &lt;- percentile_ci_email %&gt;% 
    mutate(lower_ci= paste(percentile_ci_email$lower_ci %/% 60,
                           &quot; hr and &quot;, percentile_ci_email$lower_ci %% 60,
                           &quot; min&quot;), 
           upper_ci=paste(percentile_ci_email$upper_ci %/% 60,
                          &quot; hr and &quot;, percentile_ci_email$upper_ci %% 60,
                          &quot; min&quot;))
  
  percentile_ci_email</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci          upper_ci         
##   &lt;chr&gt;             &lt;chr&gt;            
## 1 2  hr and  0  min 2  hr and  0  min</code></pre>
</div>
</div>
<div id="bidens-approval-margins" class="section level1">
<h1>Bidens Approval Margins</h1>
<p>As we saw in class, fivethirtyeight.com has detailed data on <a href="https://projects.fivethirtyeight.com/biden-approval-ratings">all polls that track the president’s approval</a></p>
<pre class="r"><code># Import approval polls data directly off fivethirtyeight website
approval_pollist &lt;- read_csv(&#39;https://projects.fivethirtyeight.com/biden-approval-data/approval_polllist.csv&#39;) 

glimpse(approval_pollist)</code></pre>
<pre><code>## Rows: 1,600
## Columns: 22
## $ president           &lt;chr&gt; &quot;Joseph R. Biden Jr.&quot;, &quot;Joseph R. Biden Jr.&quot;, &quot;Jos~
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;~
## $ modeldate           &lt;chr&gt; &quot;9/17/2021&quot;, &quot;9/17/2021&quot;, &quot;9/17/2021&quot;, &quot;9/17/2021&quot;~
## $ startdate           &lt;chr&gt; &quot;1/31/2021&quot;, &quot;2/1/2021&quot;, &quot;2/1/2021&quot;, &quot;2/2/2021&quot;, &quot;~
## $ enddate             &lt;chr&gt; &quot;2/2/2021&quot;, &quot;2/3/2021&quot;, &quot;2/3/2021&quot;, &quot;2/4/2021&quot;, &quot;2~
## $ pollster            &lt;chr&gt; &quot;YouGov&quot;, &quot;Rasmussen Reports/Pulse Opinion Researc~
## $ grade               &lt;chr&gt; &quot;B+&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;A-&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;~
## $ samplesize          &lt;dbl&gt; 1500, 1500, 15000, 1500, 15000, 1005, 1429, 15000,~
## $ population          &lt;chr&gt; &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;rv&quot;, &quot;l~
## $ weight              &lt;dbl&gt; 1.0856, 0.3308, 0.2786, 0.3086, 0.2507, 0.8741, 2.~
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,~
## $ approve             &lt;dbl&gt; 46, 52, 54, 49, 54, 57, 49, 54, 60, 50, 54, 55, 51~
## $ disapprove          &lt;dbl&gt; 38, 46, 33, 48, 34, 34, 39, 34, 32, 47, 34, 33, 46~
## $ adjusted_approve    &lt;dbl&gt; 47.2, 54.4, 52.5, 51.4, 52.5, 55.9, 49.6, 52.5, 59~
## $ adjusted_disapprove &lt;dbl&gt; 38.3, 40.1, 36.3, 42.1, 37.3, 35.1, 39.1, 37.3, 33~
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~
## $ tracking            &lt;lgl&gt; NA, TRUE, TRUE, TRUE, TRUE, NA, NA, TRUE, NA, TRUE~
## $ url                 &lt;chr&gt; &quot;https://docs.cdn.yougov.com/460mactkmh/econTabRep~
## $ poll_id             &lt;dbl&gt; 74332, 74338, 74366, 74347, 74367, 74345, 74348, 7~
## $ question_id         &lt;dbl&gt; 139593, 139642, 139733, 139654, 139734, 139652, 13~
## $ createddate         &lt;chr&gt; &quot;2/3/2021&quot;, &quot;2/4/2021&quot;, &quot;2/11/2021&quot;, &quot;2/5/2021&quot;, &quot;~
## $ timestamp           &lt;chr&gt; &quot;13:01:54 17 Sep 2021&quot;, &quot;13:01:54 17 Sep 2021&quot;, &quot;1~</code></pre>
<pre class="r"><code># Use `lubridate` to fix dates, as they are given as characters.
approval_pollist &lt;- approval_pollist %&gt;% 
  mutate(modeldate = lubridate::mdy(modeldate), 
         startdate = lubridate::mdy(startdate), 
          enddate = lubridate::mdy(enddate), 
          createddate = lubridate::mdy(createddate))</code></pre>
<div id="create-a-plot" class="section level2">
<h2>Create a plot</h2>
<p>What I would like you to do is to calculate the average net approval rate (approve- disapprove) for each week since he got into office. I want you plot the net approval, along with its 95% confidence interval. There are various dates given for each poll, please use <code>enddate</code>, i.e., the date the poll ended.</p>
<pre class="r"><code># Create confidence levels
approval_margins &lt;- approval_pollist %&gt;%
  
  #Select enddate
  filter(!is.na(enddate)) %&gt;%
  mutate(week=isoweek(enddate),
         margin=approve-disapprove) %&gt;%
  
  #Group the data
  group_by(week, subgroup) %&gt;%
  
  #Summarize data (use se formula for differences)
  summarise(
    mean=mean(margin), 
    sd=sd(margin), 
    count=n(), 
    se=sd/sqrt(count), 
    t_critical=qt(0.975, count-1), 
    lower=mean-t_critical*se, 
    upper=mean+t_critical*se)

glimpse(approval_margins)</code></pre>
<pre><code>## Rows: 99
## Columns: 9
## Groups: week [33]
## $ week       &lt;dbl&gt; 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10, 11~
## $ subgroup   &lt;chr&gt; &quot;Adults&quot;, &quot;All polls&quot;, &quot;Voters&quot;, &quot;Adults&quot;, &quot;All polls&quot;, &quot;Vo~
## $ mean       &lt;dbl&gt; 18.00, 15.85, 12.00, 20.72, 16.82, 10.89, 19.81, 15.98, 13.~
## $ sd         &lt;dbl&gt; 5.68, 8.94, 11.33, 4.37, 7.70, 6.90, 2.31, 7.60, 9.16, 3.71~
## $ count      &lt;int&gt; 8, 13, 6, 12, 19, 9, 13, 25, 14, 13, 26, 15, 13, 22, 11, 14~
## $ se         &lt;dbl&gt; 2.009, 2.480, 4.626, 1.261, 1.766, 2.300, 0.639, 1.520, 2.4~
## $ t_critical &lt;dbl&gt; 2.36, 2.18, 2.57, 2.20, 2.10, 2.31, 2.18, 2.06, 2.16, 2.18,~
## $ lower      &lt;dbl&gt; 13.250, 10.442, 0.108, 17.942, 13.110, 5.585, 18.415, 12.84~
## $ upper      &lt;dbl&gt; 22.8, 21.3, 23.9, 23.5, 20.5, 16.2, 21.2, 19.1, 18.3, 19.6,~</code></pre>
<pre class="r"><code>#Create the graph
approval_margins %&gt;% 
  filter(subgroup == &quot;Voters&quot;) %&gt;%
  ggplot(aes(x=week, y=mean)) +
  
  #Set colors 
  geom_point(color=&quot;chocolate2&quot;, size=1.5) +
  geom_line(color=&quot;chocolate2&quot;)+
  
  #Add fill between lines
  geom_ribbon(aes(ymin=lower, ymax=upper),
              color=&quot;chocolate2&quot;, 
              fill=&quot;grey87&quot;, 
              linetype=1, 
              alpha=0.5, 
              size=0.3) +
  
  #Change limits, theme, scale, facet wrap and add fitted line 
  ylim(c(-15,50)) +
  theme_bw() +
  scale_x_continuous(breaks=seq(0, 35, 13))+
  scale_y_continuous(breaks=seq(-15, 10, 2.5))+
  geom_smooth(se=FALSE) +
  
  #Add horizontal line 
  geom_hline(yintercept=0, 
             linetype=&quot;solid&quot;,
             color = &quot;chocolate2&quot;, 
             size=2) +
  
  #Add labels 
  labs( title=&quot;Estimating Approval Margins (approve-disapprove) for Joe Biden&quot;,
        subtitle = &quot;Weekly average of all polls&quot;,
        x = &quot;Week of the year&quot;,
        y = &quot;Average Approval Margin (Approve - Disapprove)&quot;) +
  NULL</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/Bidens%20Approval%20Margins-1.png" width="1152" style="display: block; margin: auto;" /></p>
</div>
<div id="compare-confidence-intervals" class="section level2">
<h2>Compare Confidence Intervals</h2>
<p>Compare the confidence intervals for <code>week 4</code> and <code>week 25</code>. Can you explain what’s going on? One paragraph would be enough.</p>
<p>The sample set differs between week 4 and week 25. The sample size on week 3 is much smaller than that of week 25 which is why the standard error is relatively higher in week 3. This leads to larger confidence intervals in week 3 compared to week 25.
As far as the data across the weeks is concerened, as sample size increases - confidence intervals shrink. The approval ratings for Joe Biden have reduced between week 4 and 25.</p>
</div>
</div>
<div id="gapminder-revisited" class="section level1">
<h1>Gapminder revisited</h1>
<p>Recall the <code>gapminder</code> data frame from the gapminder package. That data frame contains just six columns from the larger <a href="https://www.gapminder.org/data/">data in Gapminder World</a>. In this part, you will join a few dataframes with more data than the ‘gapminder’ package. Specifically, you will look at data on</p>
<ul>
<li>Life expectancy at birth (life_expectancy_years.csv)</li>
<li>GDP per capita in constant 2010 US$ (<a href="https://data.worldbank.org/indicator/NY.GDP.PCAP.KD" class="uri">https://data.worldbank.org/indicator/NY.GDP.PCAP.KD</a>)</li>
<li>Female fertility: The number of babies per woman (<a href="https://data.worldbank.org/indicator/SP.DYN.TFRT.IN" class="uri">https://data.worldbank.org/indicator/SP.DYN.TFRT.IN</a>)</li>
<li>Primary school enrollment as % of children attending primary school (<a href="https://data.worldbank.org/indicator/SE.PRM.NENR" class="uri">https://data.worldbank.org/indicator/SE.PRM.NENR</a>)</li>
<li>Mortality rate, for under 5, per 1000 live births (<a href="https://data.worldbank.org/indicator/SH.DYN.MORT" class="uri">https://data.worldbank.org/indicator/SH.DYN.MORT</a>)</li>
<li>HIV prevalence (adults_with_hiv_percent_age_15_49.csv): The estimated number of people living with HIV per 100 population of age group 15-49.</li>
</ul>
<pre class="r"><code># load gapminder HIV data
hiv &lt;- read_csv(here::here(&quot;data&quot;,&quot;adults_with_hiv_percent_age_15_49.csv&quot;))
life_expectancy &lt;- read_csv(here::here(&quot;data&quot;,&quot;life_expectancy_years.csv&quot;))

# get World bank data using wbstats
indicators &lt;- c(&quot;SP.DYN.TFRT.IN&quot;,&quot;SE.PRM.NENR&quot;, &quot;SH.DYN.MORT&quot;, &quot;NY.GDP.PCAP.KD&quot;)


library(wbstats)

worldbank_data &lt;- wb_data(country=&quot;countries_only&quot;, #countries only- no aggregates like Latin America, Europe, etc.
                          indicator = indicators, 
                          start_date = 1960, 
                          end_date = 2016)

# get a dataframe of information regarding countries, indicators, sources, regions, indicator topics, lending types, income levels,  from the World Bank API 
countries &lt;-  wbstats::wb_cachelist$countries</code></pre>
<pre class="r"><code>#cleaning life expectancy - dropping NA values
life_exp_cleaned &lt;- life_expectancy %&gt;% 
  drop_na()

# trasforming data in long format (creating columns year and life_expectancy)
life_exp_cleaned&lt;- life_exp_cleaned %&gt;% 
  pivot_longer(cols=2:302, names_to = &quot;year&quot;, values_to = &quot;life_expectancy&quot;) %&gt;% 
  #turning year in the numberic type
  mutate(year=as.numeric(year))


#giving user friendly names to columns
worldbank_cleaned &lt;- worldbank_data %&gt;% 
  rename(&quot;gdpPercap&quot;=&quot;NY.GDP.PCAP.KD&quot;, &quot;schoolEnroll&quot;=&quot;SE.PRM.NENR&quot;, &quot;mortality&quot;=&quot;SH.DYN.MORT&quot;, &quot;fertility&quot;=&quot;SP.DYN.TFRT.IN&quot;)

#join worldbank and life_exp 
table_bl&lt;-left_join(worldbank_cleaned, life_exp_cleaned, by=c(&quot;country&quot;=&quot;country&quot;, &quot;date&quot;=&quot;year&quot;))
glimpse(table_bl)</code></pre>
<pre><code>## Rows: 12,369
## Columns: 9
## $ iso2c           &lt;chr&gt; &quot;AW&quot;, &quot;AW&quot;, &quot;AW&quot;, &quot;AW&quot;, &quot;AW&quot;, &quot;AW&quot;, &quot;AW&quot;, &quot;AW&quot;, &quot;AW&quot;, ~
## $ iso3c           &lt;chr&gt; &quot;ABW&quot;, &quot;ABW&quot;, &quot;ABW&quot;, &quot;ABW&quot;, &quot;ABW&quot;, &quot;ABW&quot;, &quot;ABW&quot;, &quot;ABW&quot;~
## $ country         &lt;chr&gt; &quot;Aruba&quot;, &quot;Aruba&quot;, &quot;Aruba&quot;, &quot;Aruba&quot;, &quot;Aruba&quot;, &quot;Aruba&quot;, ~
## $ date            &lt;dbl&gt; 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, ~
## $ gdpPercap       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~
## $ schoolEnroll    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~
## $ mortality       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~
## $ fertility       &lt;dbl&gt; 4.82, 4.66, 4.47, 4.27, 4.06, 3.84, 3.62, 3.42, 3.23, ~
## $ life_expectancy &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA~</code></pre>
<pre class="r"><code>#cleaning hiv dataset
hiv_cleaned &lt;- hiv %&gt;% 
  select(-c(2:12)) 
hiv_cleaned&lt;-hiv_cleaned %&gt;% 
   pivot_longer(cols=2:23, names_to = &quot;year&quot;,
                values_to = &quot;hiv_rate&quot;) %&gt;% 
  drop_na() %&gt;% 
  mutate(year=as.numeric(year))

glimpse(hiv_cleaned)</code></pre>
<pre><code>## Rows: 3,212
## Columns: 3
## $ country  &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Algeria&quot;, &quot;Alge~
## $ year     &lt;dbl&gt; 2009, 2010, 2011, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1~
## $ hiv_rate &lt;dbl&gt; 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0~</code></pre>
<p>We used left join between world bank and life expectancy data tables since world bank has more columns and hence more relevant data compared to life expectancy.</p>
<p>We also used the left join with our previously merged data and HIV data since our intermediate table had more columns and relevant data compared to HIV.</p>
<pre class="r"><code>#joining 3 datasets in the final table
final_table&lt;-left_join(table_bl, hiv_cleaned, by=c(&quot;country&quot;=&quot;country&quot;, &quot;date&quot;=&quot;year&quot;))

#adding region from countries data set to the final table 
final_table&lt;-countries %&gt;% 
  select(region, country) %&gt;% 
  filter(!region==&quot;NA&quot;) %&gt;% 
  right_join(final_table, by=&quot;country&quot;)

final_table&lt;-final_table %&gt;% 
  rename(&quot;year&quot;=&quot;date&quot;)</code></pre>
<ol style="list-style-type: decimal">
<li>What is the relationship between HIV prevalence and life expectancy? Generate a scatterplot with a smoothing line to report your results. You may find faceting useful</li>
</ol>
<pre class="r"><code>#join hiv and life_expectancy
table_hl&lt;-inner_join(hiv_cleaned, life_exp_cleaned)
table_hl %&gt;% 
  ggplot(aes(x=hiv_rate, y=life_expectancy))+
  
  #Log transform axis to see relationship better 
  scale_x_continuous(trans = &quot;log10&quot;) +
  scale_x_continuous(trans = &quot;log10&quot;) + 
  geom_point()+
  geom_smooth()+
  
  #Set scale free so that individual plots adjust scale 
  facet_wrap(~year, scale=&quot;free&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-4-1.png" width="648" style="display: block; margin: auto;" /></p>
<ol start="2" style="list-style-type: decimal">
<li>What is the relationship between fertility rate and GDP per capita? Generate a scatterplot with a smoothing line to report your results. You may find facetting by region useful</li>
</ol>
<pre class="r"><code>#plotting gdp per capita by fertility
final_table %&gt;% 
  #filtering out NA values and years before 1990
  filter(!is.na(gdpPercap), !is.na(fertility), year&gt;=1990) %&gt;% 
  ggplot(aes(x=gdpPercap, y=fertility)) + 
  geom_point() + 
  scale_y_log10() + 
  #scale_x_log10() +
  geom_smooth(se=FALSE) +
  
  #Set scale free so that individual plots adjust scale 
  facet_wrap(~region, scales=&quot;free&quot;) +
  theme_bw() + 
  labs(title=&quot;Relationship between GDP and fertility rate&quot;, x=&quot;GDP&quot;, y=&quot;Fertility rate&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/fertility%20vs%20gdp-1.png" width="768" style="display: block; margin: auto;" /></p>
<ol start="3" style="list-style-type: decimal">
<li>Which regions have the most observations with missing HIV data? Generate a bar chart (<code>geom_col()</code>), in descending order.</li>
</ol>
<pre class="r"><code>missing_HIV  &lt;- final_table %&gt;% 
  
#Filter for certain countries to only look at a subset 
  filter(!(is.na(region))) %&gt;% 
  group_by(region) %&gt;% 
  summarise(missing_na_HIV = count(is.na(hiv_rate))) %&gt;% 
  arrange(desc(missing_na_HIV))

# Print table to inspect missing_HIV
missing_HIV</code></pre>
<pre><code>## # A tibble: 7 x 2
##   region                     missing_na_HIV
##   &lt;chr&gt;                               &lt;int&gt;
## 1 Europe &amp; Central Asia                2407
## 2 Sub-Saharan Africa                   1849
## 3 Latin America &amp; Caribbean            1847
## 4 East Asia &amp; Pacific                  1743
## 5 Middle East &amp; North Africa           1008
## 6 South Asia                            301
## 7 North America                         127</code></pre>
<pre class="r"><code>#Create bar chart: number of missing hiv data by region
ggplot(data=missing_HIV, aes(x=missing_na_HIV, y=fct_reorder(region, missing_na_HIV))) +
  geom_col() +
  theme_bw() + 
  labs(title= &quot;Bar chart for missing HIV values per region&quot;, x=&quot;Missing HIV values&quot;, y=&quot;Region&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/Missing%20HIV-1.png" width="768" style="display: block; margin: auto;" /></p>
<ol start="4" style="list-style-type: decimal">
<li>How has mortality rate for under 5 changed by region? In each region, find the top 5 countries that have seen the greatest improvement, as well as those 5 countries where mortality rates have had the least improvement or even deterioration.</li>
</ol>
<p>The first table shows the five countries per region with the greatest improvement. The second table shows the five countries per region with the least improvement.</p>
<pre class="r"><code>#extracting the difference in mortality between first and last entry
temp1 &lt;-final_table %&gt;% 
  filter(!mortality==&quot;NA&quot;) %&gt;% 
  group_by(region,country) %&gt;% 
  summarise(diff=first(mortality)-last(mortality))

#finding max 5 and min 5 countries by difference
 temp1%&gt;% 
  slice_max(order_by = diff, n=5) </code></pre>
<pre><code>## # A tibble: 33 x 3
## # Groups:   region [8]
##    region                country          diff
##    &lt;chr&gt;                 &lt;chr&gt;           &lt;dbl&gt;
##  1 East Asia &amp; Pacific   Cambodia        278. 
##  2 East Asia &amp; Pacific   Indonesia       196. 
##  3 East Asia &amp; Pacific   Timor-Leste     172. 
##  4 East Asia &amp; Pacific   Solomon Islands 168. 
##  5 East Asia &amp; Pacific   Lao PDR         166. 
##  6 Europe &amp; Central Asia Turkey          245. 
##  7 Europe &amp; Central Asia Tajikistan      118. 
##  8 Europe &amp; Central Asia Portugal        111. 
##  9 Europe &amp; Central Asia Uzbekistan      105. 
## 10 Europe &amp; Central Asia Kyrgyz Republic  92.2
## # ... with 23 more rows</code></pre>
<pre class="r"><code> temp1%&gt;% 
  slice_min(order_by = diff, n=5) </code></pre>
<pre><code>## # A tibble: 33 x 3
## # Groups:   region [8]
##    region                country                diff
##    &lt;chr&gt;                 &lt;chr&gt;                 &lt;dbl&gt;
##  1 East Asia &amp; Pacific   Palau                  17.3
##  2 East Asia &amp; Pacific   Australia              21  
##  3 East Asia &amp; Pacific   New Zealand            22.6
##  4 East Asia &amp; Pacific   Micronesia, Fed. Sts.  24  
##  5 East Asia &amp; Pacific   Japan                  37  
##  6 Europe &amp; Central Asia Monaco                  6.3
##  7 Europe &amp; Central Asia Czech Republic         12.2
##  8 Europe &amp; Central Asia Andorra                13.7
##  9 Europe &amp; Central Asia Slovak Republic        15.5
## 10 Europe &amp; Central Asia Slovenia               15.7
## # ... with 23 more rows</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Is there a relationship between primary school enrollment and fertility rate?</li>
</ol>
<p>There appears to be a negative relationship between school enrollment and fertility rate. The higher the primary school enrollment the lower the fertility rate. This trend can be observed across all regions with the exception of Europe where the school enrollment does not appear to affect fertility rate much.</p>
<pre class="r"><code>final_table %&gt;% 
  #filter out NA values
  filter(!is.na(schoolEnroll), !is.na(fertility), !is.na(region)) %&gt;% 
  
  #plotting school enrollment by fertility
  ggplot(aes(x=schoolEnroll, y=fertility)) + 
  geom_point() + 
  scale_y_log10() + 
  scale_x_log10() +
  geom_smooth(se=FALSE) +
  #facet wrap by region
  facet_wrap(~region, scales=&quot;free&quot;) +
  theme_bw() + 
  labs(title=&quot;Relationship between Primary school enrollment and fertility rate&quot;, 
       x=&quot;Primary school enrollment&quot;, 
       y=&quot;Fertility rate&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/primary%20school%20and%20fertility%20rate-1.png" width="768" style="display: block; margin: auto;" /></p>
</div>
<div id="challenge-1-excess-rentals-in-tfl-bike-sharing" class="section level1">
<h1>Challenge 1: Excess rentals in TfL bike sharing</h1>
<p>Recall the TfL data on how many bikes were hired every single day. We can get the latest data by running the following</p>
<pre class="r"><code>url &lt;- &quot;https://data.london.gov.uk/download/number-bicycle-hires/ac29363e-e0cb-47cc-a97a-e216d900a6b0/tfl-daily-cycle-hires.xlsx&quot;

# Download TFL data to temporary file
httr::GET(url, write_disk(bike.temp &lt;- tempfile(fileext = &quot;.xlsx&quot;)))</code></pre>
<pre><code>## Response [https://airdrive-secure.s3-eu-west-1.amazonaws.com/london/dataset/number-bicycle-hires/2021-08-23T14%3A32%3A29/tfl-daily-cycle-hires.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAJJDIMAIVZJDICKHA%2F20210918%2Feu-west-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20210918T113418Z&amp;X-Amz-Expires=300&amp;X-Amz-Signature=2cf132657c6f0f3e94b1f30e9b42bef9d12ccbbcf12cdb4e6ceb76a7ac96756e&amp;X-Amz-SignedHeaders=host]
##   Date: 2021-09-18 11:34
##   Status: 200
##   Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
##   Size: 173 kB
## &lt;ON DISK&gt;  C:\Users\JELENA~1.SAV\AppData\Local\Temp\Rtmpe0ifmV\file30747b9f43b9.xlsx</code></pre>
<pre class="r"><code># Use read_excel to read it as dataframe
bike0 &lt;- read_excel(bike.temp,
                   sheet = &quot;Data&quot;,
                   range = cell_cols(&quot;A:B&quot;))

# change dates to get year, month, and week
bike &lt;- bike0 %&gt;% 
  clean_names() %&gt;% 
  rename (bikes_hired = number_of_bicycle_hires) %&gt;% 
  mutate (year = year(day),
          month = lubridate::month(day, label = TRUE),
          week = isoweek(day))</code></pre>
<pre class="r"><code># Calculate monthly bike change 
monthly_expected_rentals &lt;- bike %&gt;% 
  filter(year %in% c(2016,2017,2018,2019)) %&gt;%  
  group_by(month) %&gt;% 
  summarize(expected_rentals=mean(bikes_hired))

# Calculate actual monthly rentals mean
monthly_actual_rentals &lt;- bike %&gt;% 
  filter(year %in% c(2016,2017,2018,2019,2020,2021)) %&gt;%  
  group_by(year, month) %&gt;% 
  summarize(actual_rentals=mean(bikes_hired))

#joining expected and actual rentals in single dataframe
df &lt;- inner_join(monthly_expected_rentals, monthly_actual_rentals) %&gt;% 
  #calculating up and down values - positive difference between actual and expected rentals or 0
  mutate(up = case_when((actual_rentals - expected_rentals) &gt; 0 
                        ~ actual_rentals - expected_rentals, 
                        (actual_rentals - expected_rentals) &lt;= 0 
                        ~ 0), 
         down = case_when((expected_rentals - actual_rentals) &gt; 0 
                        ~ expected_rentals - actual_rentals, 
                        (expected_rentals - actual_rentals) &lt;= 0 
                        ~ 0))
# Create the graph
ggplot(df, aes(month, expected_rentals, group=1)) +
  geom_line(color=&quot;blue&quot;) +
  geom_line(aes(month, actual_rentals)) +
  facet_wrap(~year) +
  theme(axis.text.x = element_text(size = 5)) +
  ylim(15000, 45000) +
  
  #Filling of graph - ribbons
  geom_ribbon(aes(ymin=expected_rentals,ymax=expected_rentals+up), 
              fill=&quot;#7DCD85&quot;,
              alpha=0.4) +
  geom_ribbon(aes(ymin=expected_rentals,
                  ymax=expected_rentals-down), 
              fill=&quot;#CB454A&quot;,
              alpha=0.4) +
  
  theme_minimal() + 
  
  #Label the graph 
  labs(
    title = &quot;Monthly changes in TfL bik rentals&quot;,
    subtitle = &quot;Change from monthly average shown in blue
and calculated between 2016-2019&quot;,
    caption = &quot;Source: TfL, London Data Store&quot;,
    x = &quot;&quot;,
    y = &quot;Bike rentals&quot;) +
  NULL</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/montly%20change%20in%20bikes%20-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>The second one looks at percentage changes from the expected level of weekly rentals. The two grey shaded rectangles correspond to Q2 (weeks 14-26) and Q4 (weeks 40-52).</p>
<pre class="r"><code># Calculate weekly bike change average
weekly_expected_rentals &lt;- bike %&gt;% 
  filter(year %in% c(2016,2017,2018,2019)) %&gt;%  
  group_by(week) %&gt;% 
  summarize(expected_rentals=mean(bikes_hired))

# Calculate actual weekly bike change average
weekly_actual_rentals &lt;- bike %&gt;% 
  filter(year %in% c(2016,2017,2018,2019,2020,2021)) %&gt;%  
  group_by(year, week) %&gt;% 
  summarize(actual_rentals=mean(bikes_hired))

df1 &lt;- inner_join(weekly_expected_rentals, weekly_actual_rentals) %&gt;% 
  #calculating the percentage change
  mutate(change = 100 * (actual_rentals - expected_rentals) / expected_rentals, 
         #calculating up and down values for easier plotting
         up = case_when(change &gt; 0 
                        ~ change, 
                        change &lt;= 0 
                        ~ 0), 
         down = case_when(change &gt; 0 
                        ~ 0, 
                        change &lt;= 0 
                        ~ change), 
         type = case_when(down == 0 ~ &quot;up&quot;,
                          up == 0 ~ &quot;down&quot;))

# Create the graph
ggplot(df1[1:292,], aes(week, change, group=1)) +
  
  #Create gray background
  geom_rect(aes(xmin=13,xmax=26),
            ymin=-Inf,ymax=Inf, fill=&quot;#E5E7E9&quot;, alpha=0.035) +
  geom_rect(aes(xmin=39,xmax=53),
            ymin=-Inf,ymax=Inf, fill=&quot;#E5E7E9&quot;, alpha=0.035) +
  geom_line() +
  
  #Create filling between graph 
  geom_ribbon(aes(ymin=0,ymax=up),fill=&quot;#7DCD85&quot;,alpha=0.4) +
  geom_ribbon(aes(ymin=0,ymax=down),fill=&quot;#CB454A&quot;,alpha=0.4) +
  
  #Create tickmarks at the side and set their color 
  geom_rug(aes(color=type), sides = &quot;b&quot;, 
           length = unit(0.04, &quot;npc&quot;), show.legend = FALSE) +
  scale_color_manual(values = c(&quot;#CB454A&quot;, &quot;#7DCD85&quot;))+
  
  #Facet, change theme and set scale 
  facet_wrap(~year) +
  theme_minimal() + 
  scale_y_continuous(labels = c(&quot;-50%&quot;,&quot;0%&quot;,&quot;50%&quot;,&quot;100%&quot;)) +
  scale_x_continuous(breaks = c(13,26,39,53), 
                   labels = c(&quot;13&quot;,&quot;26&quot;,&quot;39&quot;,&quot;53&quot;)) +
  
  #Label graph 
  labs(
    title = &quot;Weekly changes in TfL bike rentals&quot;,
    subtitle = &quot;%change from weekly averages 
calculated between 2016-2019&quot;,
    caption = &quot;Source: TfL, London Data Store&quot;,
    x = &quot;week&quot;,
    y = &quot;&quot;) +
  NULL</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/weekly%20change%20in%20bikes-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>For both of these graphs, you have to calculate the expected number of rentals per week or month between 2016-2019 and then, see how each week/month of 2020-2021 compares to the expected rentals. Think of the calculation <code>excess_rentals = actual_rentals - expected_rentals</code>.</p>
<p>Should you use the mean or the median to calculate your expected rentals? Why?</p>
<p>We used mean to calculate expected rentals since it incorporates the outliers well without shifting the expectation
too much in either direction. Outliers are rare (for example when the tube broke down) but they do have the probability to occur again and hence the mean is a better option in this case to calculate expected rentals.</p>
</div>
